### PR TITLE
Add missing logos for Veneto local channels

### PR DESCRIPTION
**Pull request by alesdugo**
- ANTENNA TRE VENETO: 1_0_19_2A_3000_217C_EEEE0000_0_0_0.png
- TELEPADOVA - 7 GOLD: 1_0_19_30_3000_217C_EEEE0000_0_0_0.png
- TELECHIARA: 1_0_19_32_3000_217C_EEEE0000_0_0_0.png
- TNE TELENORDEST: 1_0_19_31_3000_217C_EEEE0000_0_0_0.png

### CODE REVIEW

**Comment by alesdugo** [comment]
Let me know if further adjustments are needed. I'm happy to make any changes required.

**Comment by alesdugo** [comment]
- Televenezia: 1_0_16_36_3000_217C_EEEE0000_0_0_0.png

**Comment by alesdugo** [comment]
- TELEMANTOVA HD: 1_0_19_33_3000_217C_EEEE0000_0_0_0.png
- RADIO BIRIKINA TV: 1_0_16_37_3000_217C_EEEE0000_0_0_0.png

**Comment by LelieL91** [comment]
> Let me know if further adjustments are needed. I'm happy to make any changes required.

About the images, they seems all fine, I noticed you changed the color of "TELE VENEZIA" from black to white. I don't know what is the actual logo color, but I usually check the current logo used on the TV channel at that time. Some channels use "no background" text, just with border color. It has been a real PITA while I was preparing the repo.

Unfortunatelly I can't check if the name of the file corresponds to the actual channel Picon URL, so I can just trust your files.

Thank you for your PR. Your work is really appreciated.

**Comment by alesdugo** [comment]
> > Let me know if further adjustments are needed. I'm happy to make any changes required.
> 
> About the images, they seems all fine, I noticed you changed the color of "TELE VENEZIA" from black to white. I don't know what is the actual logo color, but I usually check the current logo used on the TV channel at that time. Some channels use "no background" text, just with border color. It has been a real PITA while I was preparing the repo.
> 
> Unfortunatelly I can't check if the name of the file corresponds to the actual channel Picon URL, so I can just trust your files.
> 
> Thank you for your PR. Your work is really appreciated.

Hi LelieL91,
Thank you for your kind feedback and for maintaining this amazing repository. I'm happy to contribute and appreciate the opportunity to help.

Regarding the "TELE VENEZIA" logo, I changed the text color from black to white after testing it on the app's background, where black text was unreadable. With the white text, the readability significantly improves, and I believe it aligns well with the channel's branding.  On the actual TV channel, the text is white. If you have a different preference, feel free to let me know, and I’ll be happy to make adjustments.

I also ensured that the file names correspond to the respective channel’s Picon URLs. If you encounter any discrepancies, please let me know, and I’ll correct them promptly.

If there’s anything else you'd like me to adjust or any specific guidelines to follow for future contributions, I’d be happy to accommodate.

Thanks again for your support and for considering my pull request!

Best regards,
alesdugo

**Comment by LelieL91** [comment]
Hi alesdugo,
Sorry for the late reply, about the logo "template", I always tried to use the current TV logo colors but I also understand readability issues caused by some clients. On Android, I'm using an app that let you choose what color background it is using for channel logos, so I don't have that problem anymore since I'm using the transparent background (on dark theme app).
The Android app I'm using is "IPTV Pro", but I honestly don't know if this setting is available for the regular version (not Pro).

Regarding the Picon URL file name, unfortunatelly I can't verify those since I'm not seeing these channels on my list, so I can just trust the PR issuer.

I made this repository since I start playing around with local IPTV and I noticed that most of the resources available online are very old and/or missing of many logos and also provided in different size (some not even compatible with most clients) and/or using poor image quality/aspect ratio + backgrounds colors.
Tired of that, I just made my own repository (usable directly as picon source) based on my channels and also tested on some Android and Windows clients like Kodi. Furthermore, since this is a public repository, that allows people like you to improve the list with missing logos, making it more complete and useful for anyone.

Thank you again for your support.

Kind regards
LelieL91

**Pull request merged**
